name = "Deathworld"
author = "crow-maki"
version = "0.1-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54bac0335317148c9c69a4cb953a93a120351b754b46434e2fb4f67317a943fb"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
